apiVersion: v1
kind: PersistentVolume
metadata:
  name: dicom-recv-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.201.8.196
    path: /mnt/shared-storage/received
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dicom-recv-pvc
  namespace: dicomrecv-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: dicom-recv-pv
  storageClassName: ""