apiVersion: v1
kind: ServiceAccount
metadata:
  name: dicomrecv-sa
  namespace: dicomrecv-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-kafka-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["initial-root-token", "kafka-1-tls"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-vault-token-access
  namespace: vault
roleRef:
  kind: ClusterRole
  name: vault-kafka-secret-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: dicomrecv-sa
    namespace: dicomrecv-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-kafka-tls-access
  namespace: kafka-ns
roleRef:
  kind: ClusterRole
  name: vault-kafka-secret-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: dicomrecv-sa
    namespace: dicomrecv-ns